// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace MartUI.Test.Unit
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// SetNameToGoodUsername - Use 'SetNameToGoodUsernameParams' to pass parameters into this method.
        /// </summary>
        public void SetNameToGoodUsername()
        {
            #region Variable Declarations
            WpfEdit uIItemEdit = this.UIMartUIWindow.UIItemCustom.UINameText.UIItemEdit;
            #endregion

            // Type 'GoodUsername' in first text box next to 'Name' label
            uIItemEdit.Text = this.SetNameToGoodUsernameParams.UIItemEditText1;
        }
        
        #region Properties
        public virtual SetNameToGoodUsernameParams SetNameToGoodUsernameParams
        {
            get
            {
                if ((this.mSetNameToGoodUsernameParams == null))
                {
                    this.mSetNameToGoodUsernameParams = new SetNameToGoodUsernameParams();
                }
                return this.mSetNameToGoodUsernameParams;
            }
        }
        
        public UIMartUIWindow UIMartUIWindow
        {
            get
            {
                if ((this.mUIMartUIWindow == null))
                {
                    this.mUIMartUIWindow = new UIMartUIWindow();
                }
                return this.mUIMartUIWindow;
            }
        }
        #endregion
        
        #region Fields
        private SetNameToGoodUsernameParams mSetNameToGoodUsernameParams;
        
        private UIMartUIWindow mUIMartUIWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'SetNameToGoodUsername'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class SetNameToGoodUsernameParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Good username' in first text box next to 'Name' label
        /// </summary>
        public string UIItemEditText = "Good username";
        
        /// <summary>
        /// Type 'GoodUsername' in first text box next to 'Name' label
        /// </summary>
        public string UIItemEditText1 = "GoodUsername";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIMartUIWindow : WpfWindow
    {
        
        public UIMartUIWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "MartUI";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MartUI");
            #endregion
        }
        
        #region Properties
        public UIItemCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new UIItemCustom(this);
                }
                return this.mUIItemCustom;
            }
        }
        #endregion
        
        #region Fields
        private UIItemCustom mUIItemCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemCustom : WpfCustom
    {
        
        public UIItemCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.CreateUserView";
            this.WindowTitles.Add("MartUI");
            #endregion
        }
        
        #region Properties
        public UINameText UINameText
        {
            get
            {
                if ((this.mUINameText == null))
                {
                    this.mUINameText = new UINameText(this);
                }
                return this.mUINameText;
            }
        }
        #endregion
        
        #region Fields
        private UINameText mUINameText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UINameText : WpfText
    {
        
        public UINameText(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfText.PropertyNames.Name] = "Name";
            this.WindowTitles.Add("MartUI");
            #endregion
        }
        
        #region Properties
        public WpfEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.SearchConfigurations.Add(SearchConfiguration.NextSibling);
                    this.mUIItemEdit.WindowTitles.Add("MartUI");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUIItemEdit;
        #endregion
    }
}
